fixtures:
  repositories:
    stdlib:
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib"
      ref: "4.7.0"
    apache:
      repo: "git://github.com/puppetlabs/puppetlabs-apache"
      ref: "1.5.0"
    htpasswd:
      repo: "git://github.com/leinaddm/puppet-htpasswd"
      ref: "v0.0.3"
    concat:
      repo: "git://github.com/puppetlabs/puppet-concat"
      ref: "1.2.3"
  symlinks:
    lma_infra_alerting: "#{source_dir}"
    nagios: "#{source_dir}/../nagios"
